title: "Articles"
description: "A collection of articles"
author: "abednarski79"
baseurl: "/articles" # This matches your repository name
url: "https://abednarski79.github.io" # Your GitHub Pages domain
markdown: kramdown

# Optional: Plugins (if needed)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
